### ISSUE TITLE
Did MMFS get a feature like BEEB n in SmartSpi where n is the BEEBn.MMB file to use?

### ISSUE THREAD

**Issue by richard-broadhurst** [hoglet67/MMFS#34]
Did MMFS get a feature like BEEB n in SmartSpi where n is the BEEBn.MMB file to use?
There was talk of larger .MMB files, possibly as concatenations of .MMB files, possibly with all but the last having to be 511 discs in size.

**Comment by hoglet67** [comment]
Since version 1.50, MMFS allows larger MMB files (extending the size in chunks of 511 images) upto a maximum of 16 chunks (8176 images)

An extended MMB file is basically just N of the original 511 disk MMB files (aka chunks) concatenated together. Byte 8 in the first chunk indicates how many chunks there are. The value store there is &Ax where x is the number of additional chunks. So a MMB file with 4 chunks (2044 images) would have byte 8 set to &A3.

The *DIN command can now take an argument that's larger than 511, so all disks are immediately accessible without needing to swap chunks.

It's also possible to set the "base chunk" using the *DBASE command; this default to chunk 0. This is stored in the byte 9 of the MMB file. So if you did want to think of each chunk as a seperate 511 disk MMB file, then that's supported as well.

The dev thread is worth a read:
[Extending the MMB format beyond 511 disks](https://stardot.org.uk/forums/viewtopic.php?t=23435)

Stephen's MMB_Utils also supports this extended format if you want to scipt the creation of a larger games archive. There are some examples of it being used here:
https://stardot.org.uk/forums/viewtopic.php?p=336172#p336172

Stephen also wrote some documentation for the extended format here:
https://sweh.spuddy.org/Beeb/mmb_utils.html
Skip to the section titles "Disk Format"

I've been using this for a couple of years now and it's very stable.

I'll be on the dev call this evening if you want to chat about this.

Dave

**Comment by richard-broadhurst** [comment]
Thankyou hoglet, very helpful as always.
Looks like I have some eprom programming to do :)
