### ISSUE TITLE
MMFS with BeebEm 4.19

### ISSUE THREAD

**Issue by marrold** [hoglet67/MMFS#36]
Thanks for creating MMFS!

I'm attempting to follow these [instructions ](https://github.com/hoglet67/MMFS/wiki/Using-MMFS-or-MMFS2-in-BeebEm) to mount a MMFS v1 .mmb file in BeebEm, however it complains that `C://beeb.mmb` is not present. 

I've attempted placing a mmc.cfg file in the BeebEm program directory, the directory in My Documents, and the same directory as the .dll but it seems like the cfg isn't being read and it's still trying to load `C://beeb.mmb`. I've double checked and there's no carriage returns or other characters in the file, just the path to the .mmb

Has something changed in 4.19? Any thoughts appreciated.

**Comment by hoglet67** [comment]
The MMBeebXL.dll extension to BeebEm is not something I really support, because I don't routinely use BeebEm (or Windows) myself.

But I'll try to help...

The wiki page linked to an old version of MMBeebXL.dll that was [posted on stardot](https://stardot.org.uk/forums/viewtopic.php?p=296468) in 2019.

Since then, Martin Mather has released a new version on github:
https://github.com/mmbeeb/MMBeebXL

With this new version, the default path for the BEEB.MMB file is Documents\BeebEm\DiscIms\beeb.mmb

So you should't need to mess around with mmc.cfg files

Note, this new version also needs MMFS 1.50 or later to work, as the hardware address of the MMC interface on the Model B changed from FE18 to FE1C (so it didn't conflict with the Econet support that BeebEm now has).

I've updated the wiki page to reflect these changes.
https://github.com/hoglet67/MMFS/wiki/Using-MMFS-or-MMFS2-in-BeebEm

I'd recommend you try this new version, and stick to the default path for the beeb.mmb file.

**Comment by marrold** [comment]
Yup that has worked, thanks for the speedy response

**Comment by hoglet67** [comment]
Glad that sorted it.
